{% set name = "pydmd" %}
{% set version = "2024.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydmd-{{ version }}.tar.gz
  sha256: 5a14fb5432a21d7b37818fe387bf7bf97584ae97f9de5aeda34d24855eb04100

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - typing_extensions >=4.7.0
    - h5netcdf
    - xarray
    - python >=3.7
    - numpy <2
    - scipy >=1.6.0
    - matplotlib-base
    - scikit-learn

test:
  imports:
    - pydmd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mathLab/PyDMD
  summary: Python Dynamic Mode Decomposition.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
